export { SHIPMENT_STATUSES, ADMIN_DAYS, SECONDS_PER_TRANSIT_DAY, MAX_TRANSIT_DAYS, SHIPMENT_STATUS_LABELS, ADMIN_SHIPMENT_STATUS_LABELS, STATUS_VARIANT_MAP, COURIER_ACTION_MAP } from "./shipment";
export type { ShipmentStatus } from "./shipment";
